BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Switches" (
	"ID"	INTEGER NOT NULL ,
	"Type"	TEXT,
	"IP"	TEXT NOT NULL,
	"MAC"	TEXT,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "Ports" (
	"Nr"	INTEGER NOT NULL,
	"Switch" INTEGER NOT NULL,
	"Name"	TEXT,
	"Type"	TEXT,
	"MAC"	TEXT,
	PRIMARY KEY("Nr", "Switch"),
	FOREIGN KEY("Switch") REFERENCES "Switches"("ID")
);
CREATE TABLE IF NOT EXISTS "DeviceLog" (
	"Time"	INTEGER NOT NULL,
	"Mac"	TEXT NOT NULL,
	"Switch"	INTEGER NOT NULL,
	"VLAN"	TEXT,
	"Port"	INTEGER,
	"IP"	TEXT,
	"Hostname"	TEXT,
	PRIMARY KEY("Time","Mac","Switch"),
	FOREIGN KEY("Switch") REFERENCES "Switches"("ID")
);
COMMIT;
