BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Switches" (
	"ID"	INTEGER NOT NULL,
	"Type"	TEXT NOT NULL,
	"IP"	TEXT NOT NULL,
	"MAC"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Device Log" (
	"Time"	INTEGER NOT NULL,
	"Mac"	TEXT NOT NULL,
	"Switch"	INTEGER,
	"VLAN"	TEXT,
	"Port"	INTEGER,
	"IP"	TEXT,
	"Hostname"	TEXT,
	PRIMARY KEY("Time","Mac","Switch","VLAN"),
	FOREIGN KEY("Switch") REFERENCES "Switches"("ID")
);
COMMIT;
